# Generated by Django 3.1.7 on 2021-04-29 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('purchase_date', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('cost_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stock')),
            ],
        ),
    ]
