# Generated by Django 3.1.7 on 2021-04-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_items_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
    ]
