# Generated by Django 3.1.7 on 2021-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('admin', 'Admin'), ('nurse', 'Nurse'), ('accountant', 'Accountant')], default='patient', max_length=20),
        ),
    ]
