# Generated by Django 3.1.7 on 2021-04-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210425_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('admin', 'Admin'), ('nurse', 'Nurse'), ('accountant', 'Accountant'), ('lab_tech', 'Lab Tech')], default='patient', max_length=20),
        ),
    ]
