# Generated by Django 3.1.7 on 2021-04-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210425_0806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabAssistant',
            new_name='LabTechnician',
        ),
        migrations.AlterModelOptions(
            name='labtechnician',
            options={'verbose_name_plural': 'Lab Technician'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='aadhar_number',
            field=models.BigIntegerField(default=123, verbose_name='Aadhar Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='empCategory',
            field=models.CharField(blank=True, max_length=20, verbose_name='Employee Category'),
        ),
    ]
