# Generated by Django 3.1.7 on 2021-04-21 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('filed_date', models.DateTimeField()),
                ('closed_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('closed', 'CLOSED')], default='open', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_receptionist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
