# Generated by Django 3.1.7 on 2021-03-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='closed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
