# Generated by Django 3.1.7 on 2021-03-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20210311_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_closed',
            field=models.BooleanField(default=False),
        ),
    ]
