# Generated by Django 3.1.7 on 2021-03-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_case_case_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_closed',
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'OPEN'), ('closed', 'CLOSED')], default='open', max_length=10),
        ),
    ]
