# Generated by Django 3.1.7 on 2021-03-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20210314_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='closed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='filed_date',
            field=models.DateTimeField(),
        ),
    ]
